const express = require("express")
const userRoutes = require("./userRoutes")
const dashboardRoutes = require("./dashboard")
const app = express()
const cors = require("cors")
app.use(cors())
app.use(express.json())
app.use("/auth", userRoutes)
app.use("/dashboard", dashboardRoutes)
app.listen(4000, () => {
    console.log("Server starting on port 4000")
})
